### PR TITLE
fix(recipe-contact-info): remove d-of-hidden

### PR DESCRIPTION
**Pull request by juliodialpad**
# Fix Recipe Contact Info

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

Removed `d-of-hidden` class from default_list_item as I don't see any reason to keep it and it is breaking the behavior if it contains a popover anchor inside it.

## :bulb: Context

This is related with https://github.com/dialpad/firespotter/pull/27100, the real issue is that contact-info has a `d-of-hidden` class that prevents the popover anchor element to have the required space to display properly.

## :pencil: Checklist

- [x] I have reviewed my changes
- [ ] I have added tests
- [ ] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [x] I have validated components keyboard navigation
- [ ] I have considered the performance impact of my change
- [ ] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

### CODE REVIEW

**Review by braddialpad — COMMENTED** [review]
I agree with this but I'm a bit worried about it breaking something in product. Can we migrate this to dialpad and check instances of dt-list-item?

**Comment by juliodialpad** [comment]
> I agree with this but I'm a bit worried about it breaking something in product. Can we migrate this to dialpad and check instances of dt-list-item?

Sure, I'll migrate and test before merging

**Review by braddialpad — APPROVED** [review]

**Comment by juliodialpad** [comment]
Tested all over the places where `DtListItem` was being used and everything looks fine. I think we are safe, merging this.

**Comment by MikaDialpad** [comment]
This was originally added to enable truncation of the content https://github.com/dialpad/dialtone-vue/pull/604. It's still possible when using a custom type, but we could consider adding this conditionally as a prop or use a generic `contentClass` or something to allow passing any classes to this element.

EDIT: Ugh I forgot that there's no interface currently to the default list item as it's being wrapped by the DtListItem, so the suggestion above probably wouldn't work...

**Pull request merged**
