### PR TITLE
docs: fix avatar images broken

### PR DESCRIPTION
**Pull request by juliodialpad**
# Vue 3 version of #1234

### CODE REVIEW

**Review by braddialpad — CHANGES_REQUESTED** [review]
Hmm seems something is not working in this vue 3 version. No visual changes detected. Have a look at avatar variants in the preview, it's still showing initials.

**Comment by iropolo** [comment]
> Hmm seems something is not working in this vue 3 version. No visual changes detected. Have a look at avatar variants in the preview, it's still showing initials.

Attaching info:

Vue2:
image


Vue3:
image

**Comment by juliodialpad** [comment]
@braddialpad @iropolo Forgot to migrate to vue 3 prepending with `$attrs.`, should be fixed now.

**Comment by iropolo** [comment]
Not related but catch this issue

image

Could we create a ticket to fix it, please?

Vue2
image


Looks good your fix to me. Thanks

**Review by iropolo — APPROVED** [review]
Looks good to me now, thanks

**Comment by juliodialpad** [comment]
> Not related but catch this issue
> 
> image
> Could we create a ticket to fix it, please?
> 
> Vue2 image
> 
> Looks good your fix to me. Thanks

Sure, I'll create a ticket and fix it quickly if simple enough

**Review by braddialpad — APPROVED** [review]
Looks good now, thanks

**Pull request merged**
