### PR TITLE
feat(emoji-picker): with popover variant and code improvement

### PR DESCRIPTION
**Pull request by iropolo**
# Emoji picker with popover variant

## :hammer_and_wrench: Type Of Change

- [x] Feature

## :book: Description

The `with popover` variant and this improvements ease the work on the Message Input in the conversation view recipe.

We also fix an accessibility issue caused by to be wrapped inside the dt-popover.

### CODE REVIEW

**Comment by iropolo** [comment]
@sanjeevdialpad

This will help on the building of the Message Input component.

**Review by braddialpad — COMMENTED** [review]
Looks good, but can we add this story into the docs page so developers can click "show code" and see how to implement it?

Screenshot 2023-06-15 at 10 10 06 AM

**Comment by iropolo** [comment]
> Looks good, but can we add this story into the docs page so developers can click "show code" and see how to implement it?
> 
> Screenshot 2023-06-15 at 10 10 06 AM

yass, thats looks great, but how I can add it? I can see these ones

image


But not that one 🤔 , it is the same or Im missing sth?

**Comment by braddialpad** [comment]
> yass, thats looks great, but how I can add it?

in the mdx file your

```
<Canvas>
  <Story of={EmojiPickerStories.WithPopover} />
</Canvas>
```

Should automatically do it. You probably don't need to include the manual code example anymore now that storybook example code actually works in storybook 7.

**Comment by iropolo** [comment]
> > yass, thats looks great, but how I can add it?
> 
> in the mdx file your
> 
> ```
> <Canvas>
>   <Story of={EmojiPickerStories.WithPopover} />
> </Canvas>
> ```
> 
> Should automatically do it. You probably don't need to include the manual code example anymore now that storybook example code actually works in storybook 7.

Ohh you mean the `'show code'`... you know I get confused because the `withPopover` doesn't has anything different than the previous story...

I guess I can let the code there as how I did now, because Im showing the `dt-popover` implementation 🤔 .

Im wonder why the `'show code'` on the `withPopover` doesnt show the popover code....

**Comment by braddialpad** [comment]
> > > yass, thats looks great, but how I can add it?
> > 
> > 
> > in the mdx file your
> > ```
> > <Canvas>
> >   <Story of={EmojiPickerStories.WithPopover} />
> > </Canvas>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Should automatically do it. You probably don't need to include the manual code example anymore now that storybook example code actually works in storybook 7.
> 
> Ohh you mean the `'show code'`... you know I get confused because the `withPopover` doesn't has anything different than the previous story...
> 
> I guess I can let the code there as how I did now, because Im showing the dt-popover implementation 🤔 .

Oh yeah.. looks like it is only showing the emoji-picker and doesn't include the wrapper dt-popover. I guess that's just how it works. In this case the manual example is fine then.

**Review by braddialpad — APPROVED** [review]

**Pull request merged**
