### PR TITLE
NO-MERGE: Percy scroller fix

### PR DESCRIPTION
**Pull request by iropolo**
Testing percy action

### CODE REVIEW

**Comment by iropolo** [comment]
Moved to ready to review to try trigger the visual_tests action

**Comment by juliodialpad** [comment]
You can trigger the action by adding the 'visual-test-ready' tag

**Comment by iropolo** [comment]
> You can trigger the action by adding the 'visual-test-ready' tag

Cool, Idk why the previous PR added automatically the 'visual-test-ready' tag

**Comment by iropolo** [comment]
Percy action working well. is ignoring dynamic scroller closing PR.

**Pull request closed without merging**
