### PR TITLE
chore(deps): update deps

### PR DESCRIPTION
**Pull request by josedialpad**
# update deps

## :hammer_and_wrench: Type Of Change

- [ ] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :pencil: Checklist

- [x] I have reviewed my changes
- [ ] I have added tests
- [ ] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [ ] I have validated components keyboard navigation
- [ ] I have considered the performance impact of my change
- [ ] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

### CODE REVIEW

**Comment by braddialpad** [comment]
Looks like we got some new accessibility errors due to the update. Fix or just disable for now.

**Review by braddialpad — CHANGES_REQUESTED** [review]
Lint errors as mentioned above

**Comment by josedialpad** [comment]
> Lint errors as mentioned above

Looking into it.

**Comment by josedialpad** [comment]
> Looks like we got some new accessibility errors due to the update. Fix or just disable for now.

Disabled the rule in most cases. The main issue for fixing it is that we can't attach the event listeners into the slot

**Review by braddialpad — APPROVED** [review]
Thanks!

**Pull request merged**
