### PR TITLE
feat(toggle): add size prop

### PR DESCRIPTION
**Pull request by josedialpad**
# add size prop

## :hammer_and_wrench: Type Of Change

- [ ] Fix
- [x] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

Add prop for `size` with the values: `md` (default) and `sm`

~⚠️ Depends on the dialtone changes on this branch: [feature/toggle-small-variant](https://github.com/dialpad/dialtone/tree/feature/toggle-small-variant)~
Updated PR with the changes released in [Dialtone 7.4.0](https://github.com/dialpad/dialtone/releases/tag/v7.4.0)

## :bulb: Context

Jira ticket: https://dialpad.atlassian.net/browse/DT-737

Changes included in this PR:
- [x] add prop for size: toggles .d-toggle--small class.
- [ ] add prop to hide icons: suppresses .d-toggle__inner. https://github.com/dialpad/dialtone-vue/pull/573
- [ ] add prop for indeterminate state. https://github.com/dialpad/dialtone-vue/pull/579

## :pencil: Checklist

- [x] I have reviewed my changes
- [x] I have added tests
- [ ] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [ ] I have validated components keyboard navigation
- [ ] I have considered the performance impact of my change
- [ ] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

### CODE REVIEW

**Comment by braddialpad** [comment]
> ⚠️ Depends on the dialtone changes on this branch: [feature/toggle-small-variant](https://github.com/dialpad/dialtone/tree/feature/toggle-small-variant)

What's happening with this branch is it going to be PR'd?

**Comment by josedialpad** [comment]
> > ⚠️ Depends on the dialtone changes on this branch: [feature/toggle-small-variant](https://github.com/dialpad/dialtone/tree/feature/toggle-small-variant)
> 
> What's happening with this branch is it going to be PR'd?

It should be added in dialtone. I'll create a PR from that branch with the changes Francis made. cc @francisrupert 

Update: created PR https://github.com/dialpad/dialtone/pull/725

**Comment by josedialpad** [comment]
@braddialpad updated PR with the changes already included in Dialtone. This is the main branch to collect all the features: new small size, show icon prop and indeterminate state. I created a separated PR for each feature to facilitate CR but let me know if you find this way more confusing than practical.

**Review by braddialpad — APPROVED** [review]

**Comment by braddialpad** [comment]
> @braddialpad updated PR with the changes already included in Dialtone. This is the main branch to collect all the features: new small size, show icon prop and indeterminate state. I created a separated PR for each feature to facilitate CR but let me know if you find this way more confusing than practical.

No prob, I'm fine with smaller PRs they're much easier to review.

**Pull request merged**
