### PR TITLE
fix(sidebar): prevent sidebar shrinking

### PR DESCRIPTION
**Pull request by eabrakov**
# Fix sidebar shrinking

https://dialpad.atlassian.net/browse/DP-80071

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :pencil: Checklist

- [x] I have reviewed my changes
- [ ] I have added tests
- [ ] I have added all relevant documentation
- [x] I have validated components with a screen reader
- [x] I have validated components keyboard navigation
- [x] I have considered the performance impact of my change
- [x] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

## :link: Sources

Jira: https://dialpad.atlassian.net/browse/DP-80071

### CODE REVIEW

**Review by juliodialpad — COMMENTED** [review]
We're no longer using dialtone utility classes at component level.

Please close this PR and add the custom CSS to the corresponding dialtone component on the dialtone repo.

**Comment by eabrakov** [comment]
@juliodialpad sorry, but if the width is set here, we can't do this on dialtone side properly, basically this element exists only in dialtone-vue

**Comment by braddialpad** [comment]
> @juliodialpad sorry, but if the width is set here, we can't do this on dialtone side properly, basically this element exists only in dialtone-vue

`.d-root-layout__sidebar` right?

https://github.com/dialpad/dialtone/blob/staging/lib/build/less/components/root-layout.less

**Comment by eabrakov** [comment]
Oh, sorry, got you point

**Pull request closed without merging**
