### PR TITLE
feat: migrate to vite and storybook 7.0

### PR DESCRIPTION
**Pull request by braddialpad**
# feat: migrate to vite and storybook 7.0

## :hammer_and_wrench: Type Of Change

- [ ] Fix
- [x] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

I don't really expect you guys to review this throughly since it's so huge, but maybe go through the preview of the new storybook and try to find any problems you can.

I doubt this will be merged in quickly as there are still some weird issues I'd like to figure out before going live with it, it needs to be done on the vue 3 branch, and I need to test the new bundle in product, make sure it still works etc. Maybe will release a beta before merging into staging.

The Vite migration was not too bad, the main thing is you have to put extensions on all of your Vue imports. Tedious but easy enough to do.

The storybook 7.0 migration was a different story (pun not intended). There were TONS of breaking changes especially in `.mdx` and `.stories.js` files. There were some tools to help but also lots that had to be done manually.

I've already merged in the jest changes and configured them to work with the new infrastructure.

see: https://storybook.js.org/docs/vue/migration-guide

## :bulb: Context

Our infrastructure is getting outdated and is frustrating to work with. As part of getting on top of tech debt I decided to update to Vite and Storybook 7. Storybook 7 is Storybook's largest update of all time. This is obviously a huge change and very disruptive but it should make things easier for the immediate future. Storybook seems to have much better vue support, code examples actually display now!

The best part of this. NO MORE BABEL. We're now using pure ES Modules (except jest still uses some babel, but that will be gone as well if we start using Vitest).

## :pencil: Checklist

- [x] I have reviewed my changes
- [x] I have added tests
- [x] I have added all relevant documentation
- [x] I have validated components with a screen reader
- [x] I have validated components keyboard navigation
- [x] I have considered the performance impact of my change
- [x] I have checked that my change did not significantly increase bundle size
- [x] I am exporting any new components or constants in the index.js in the component directory
- [x] I am exporting any new components or constants in the index.js in the root

## :crystal_ball: Next Steps

- ~~Test produced bundle in product.~~
- Write documentation and create blog post of the changes.
- ~~transform to new CSF 3 format.~~
- Do the same thing on vue 3 branch (this is not going to be fun).

## :camera: Screenshots / GIFs

Screenshot 2023-04-26 at 5 19 39 PM

## :link: Sources

https://storybook.js.org/docs/vue/migration-guide

### CODE REVIEW

**Comment by juliodialpad** [comment]
I've been playing around with this a bit and everything seems to be working pretty well, just noticed that when you are clicking through different stories, you can notice a delay between stories rendering. Do you know why is that happening?

**Comment by braddialpad** [comment]
> I've been playing around with this a bit and everything seems to be working pretty well, just noticed that when you are clicking through different stories, you can notice a delay between stories rendering. Do you know why is that happening?

Yep, seems to be "On-demand story loading" which storybook changed in V7 https://storybook.js.org/docs/react/configure/overview#on-demand-story-loading

Unfortunately it doesn't even let me disable it if I try:

Screenshot 2023-04-27 at 10 59 07 AM

**Comment by braddialpad** [comment]
New bundle tested and working in dialpad.

**Comment by iropolo** [comment]
Hey, this migration is awesome and Im sure it is not easy, I will try to help you out on this!.
This will be huge and it will take time.

I will start with something "easy" but we need to communicate each other more frequently. This mean I will ask you about something right now lol.

I can see some components has issues to show the Docs file. 
For example the Banner component.

And what I found there is we are using in some cases the ButtonStories which and I dont know why, maybe its some random copy/paste or migration error.
I just replaced it with the correct BannerStories and its done. 
It works the same as https://vue.dialpad.design/deploy-previews/pr-839/?path=/docs/components-banner--default

My question is, it would be helpful for you if I take this Docs errors to start with sth? so you can focus on another more important part of the migration.

Happy to see this initiative, we should always try to be on the latest technology updates :)

**Comment by braddialpad** [comment]
> And what I found there is we are using in some cases the ButtonStories which and I dont know why, maybe its some random copy/paste or migration error.

Yeah definitely some sort of copy paste error. Go ahead and make the fix, these sort of things are exactly what I'm trying to find before merging.

**Pull request merged**
