### PR TITLE
fix(popover): null protection

### PR DESCRIPTION
**Pull request by braddialpad**
# fix(popover): null protection

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

Couple of null protection fixes on popover. 

## :bulb: Context

Some errors were being triggered in sentry due to this.

### CODE REVIEW

**Comment by juliodialpad** [comment]
Do you think this relates to this? 

https://dialpad.atlassian.net/browse/DP-68338

I've been investigating about it but have not been able to reproduce it.

**Comment by braddialpad** [comment]
> 

I think my recent change will actually fix this. https://github.com/dialpad/firespotter/commit/1f8e7520c66f0c281a8ede2de4f9723b0ee16a0b#diff-1d3883cc963634603b675b60cb4f8c6911046990a1f74433ba1ae9b1ed925483L376

It is not necessary to do this focusInput after changing to DtDropdown

**Comment by juliodialpad** [comment]
> > 
> 
> I think my recent change will actually fix this. [dialpad/firespotter@1f8e752#diff-1d3883cc963634603b675b60cb4f8c6911046990a1f74433ba1ae9b1ed925483L376](https://github.com/dialpad/firespotter/commit/1f8e7520c66f0c281a8ede2de4f9723b0ee16a0b#diff-1d3883cc963634603b675b60cb4f8c6911046990a1f74433ba1ae9b1ed925483L376)
> 
> It is not necessary to do this focusInput after changing to DtDropdown

Nice! Thanks a lot brad, I'll update that ticket then.

**Review by juliodialpad — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
