### PR TITLE
fix(contact-info): overlay icon alignment

### PR DESCRIPTION
**Pull request by fabiangarga**
# (contact_info): fix overlay icon alignment

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

Update `dt-avatar` overlay class to fix the alignment when using the new callbar 

## :pencil: Checklist

- [ ] I have reviewed my changes
- [ ] I have added tests
- [ ] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [ ] I have validated components keyboard navigation
- [ ] I have considered the performance impact of my change
- [ ] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

### CODE REVIEW

**Comment by iropolo** [comment]
Hello!, Im not sure this class is getting any effect... 🤔 

image

**Review by juliodialpad — CHANGES_REQUESTED** [review]
Please provide screenshots before and after this change

**Comment by fabiangarga** [comment]
Thanks @juliodialpad @iropolo, my bad, updated with the wrong DT class.

Here are some screenshots

Before:
Screenshot 2023-08-07 at 19 11 54

After:
Screenshot 2023-08-07 at 19 13 10

**Comment by iropolo** [comment]
Hmm ok... it is strange why the svg with `width: 100%` didnt fix it, seems like there is some width issue some around...
But okay Im guessing we can double check this with the `justify-content: center` property.

Im wondering if we can add this in the `.d-avatar__overlay` class in `avatar.vue` component to ensure the svg will be always in the middle... what you think @juliodialpad ?

**Comment by fabiangarga** [comment]
> Im wondering if we can add this in the `.d-avatar__overlay` class in `avatar.vue` component to ensure the svg will be always in the middle... what you think @juliodialpad ?

Just in case, to only affect the new callbar I added to this recipe.

**Comment by iropolo** [comment]
There is a chance where this is a issue that need to be fixed in dialtone side, lets wait for @juliodialpad  confirmation then I can create the PR for it.

**Comment by juliodialpad** [comment]
I'm not sure where the issues are coming from, the [example on documentation](https://vue.dialpad.design/?path=/story/recipes-list-items-contact-info--variants) works perfectly without that class. Give me a minute to check on product if they have some custom class that's breaking the implementation

**Comment by iropolo** [comment]
> I'm not sure where the issues are coming from, the [example on documentation](https://vue.dialpad.design/?path=/story/recipes-list-items-contact-info--variants) works perfectly without that class. Give me a minute to check on product if they have some custom class that's breaking the implementation

Maybe this help to debug,

Take a look on https://vue.dialpad.design/?path=/story/recipes-list-items-contact-info--variants

Initially the svg has 100% of width, if you update it for example to 25px you can replicate the issue.

Screenshot 2023-08-09 at 13 28 30

So what Im guessing is the 100% of width in the svg is not enough to ensure svg in the middle.

>  it is strange why the svg with `width: 100%` didnt fix it, seems like there is some width issue some around..

🤔

**Comment by juliodialpad** [comment]
That makes sense, I'll investigate on product why they're changing the size.

But this should be fixed on `DtAvatar`, it's ok to add `justify-content: center` to be sure the icon is always in the middle.

Please close this PR, I'll create another one with the proper fix.

**Comment by fabiangarga** [comment]
> That makes sense, I'll investigate on product why they're changing the size.
> 
> But this should be fixed on `DtAvatar`, it's ok to add `justify-content: center` to be sure the icon is always in the middle.
> 
> Please close this PR, I'll create another one with the proper fix.

Got it, I will add you to the Jira ticket then. Thanks.

**Pull request closed without merging**
