### PR TITLE
fix(recipe-callbar-button-with-popover): change event name and sync open state

### PR DESCRIPTION
**Pull request by SheldonDialpad**
# fix(recipe-callbar-button-with-popover): change event name and sync open state

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

1. The arrow click event name should change to `arrow-click`, or we'll get "vue/v-on-event-hyphenation" warning.
2. The open state should be synced with `openPopover` property, or it will cause issue https://dialpad.atlassian.net/browse/DP-80569

## :pencil: Checklist

- [x] I have reviewed my changes
- [ ] I have added tests
- [ ] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [ ] I have validated components keyboard navigation
- [ ] I have considered the performance impact of my change
- [ ] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

## :crystal_ball: Next Steps

Raise PR in UV and add `arrow-click` event handle in parent component.

## :link: Sources

https://dialpad.atlassian.net/browse/DP-80569

### CODE REVIEW

**Review by iropolo — CHANGES_REQUESTED** [review]
Thanks,
Please find all `arrowClick` and replace it with `arrow-click` there is some in tests and in stories files.
Be aware of those element which it is not necessary to update like constants in test and `onArrowClick` in storie.

**Review by SheldonDialpad — COMMENTED** [review]
> Thanks, Please find all `arrowClick` and replace it with `arrow-click` there is some in tests and in stories files. Be aware of those element which it is not necessary to update like constants in test and `onArrowClick` in storie.

Thanks for reviewing. I just updated the unit tests.

**Review by iropolo — CHANGES_REQUESTED** [review]
Please update in `callbar_button_with_popover_default.story.vue`
`@arrow-click="onClick"`
to
`@arrow-click="onArrowClick"`

update in `callbar_button_with_popover.stories.js`
`onArrowClick: action('arrowClick'),`
to
`onArrowClick: action('arrow-click'),`

now we will see the action in storybook.

**Review by iropolo — APPROVED** [review]
Thanks for the improvement!!

**Pull request merged**
