### PR TITLE
fix(avatar): dynamic icon sizes

### PR DESCRIPTION
**Pull request by juliodialpad**
# Fix (Avatar): Dynamic icon sizes

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

Added back icon sizes according to avatar size

## :bulb: Context

We were missing the dynamic icon size according to the avatar's selected size, can't remember when we loosed this functionality.

## :pencil: Checklist

- [x] I have reviewed my changes
- [ ] I have added tests
- [ ] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [ ] I have validated components keyboard navigation
- [ ] I have considered the performance impact of my change
- [ ] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

## :camera: Screenshots / GIFs

image

### CODE REVIEW

**Comment by braddialpad** [comment]
> can't remember when we loosed this functionality.

I'm guessing during the dialtone 8 migration. Hmm was there some intentional reason we did this? Maybe it was supposed to be all handled via CSS?

**Comment by braddialpad** [comment]
~~Seems like the avatar is set to size to 100% of the canvas size. https://github.com/dialpad/dialtone/blob/3231f28b2cbe7375afc587ad08ab8a89194fdfec/lib/build/less/components/avatar.less#L49~~

~~Are there situations where we don't want that?~~

NM this is for images only

**Comment by juliodialpad** [comment]
> > can't remember when we loosed this functionality.
> 
> I'm guessing during the dialtone 8 migration. Hmm was there some intentional reason we did this? Maybe it was supposed to be all handled via CSS?



> > can't remember when we loosed this functionality.
> 
> I'm guessing during the dialtone 8 migration. Hmm was there some intentional reason we did this? Maybe it was supposed to be all handled via CSS?

Seems like longer ago, can't find the commit where we removed the sizing from the icon, or maybe we never used that constant really?

**Comment by juliodialpad** [comment]
> Seems like the avatar is set to size to 100% of the canvas size. https://github.com/dialpad/dialtone/blob/3231f28b2cbe7375afc587ad08ab8a89194fdfec/lib/build/less/components/avatar.less#L49
> 
> Are there situations where we don't want that?

Don't really know, just thought It'd look better with its corresponding icon sizes and realized that constant was unused

Before
image

After
image

**Comment by braddialpad** [comment]
> Don't really know, just thought It'd look better with its corresponding icon sizes and realized that constant was unused

Yeah that definitely looks bad.

I think maybe we should set this on the dialtone (CSS/LESS) side though. perhaps we can still keep this prop here to override if necessary

**Comment by juliodialpad** [comment]
> > Don't really know, just thought It'd look better with its corresponding icon sizes and realized that constant was unused
> 
> Yeah that definitely looks bad.
> 
> I think maybe we should set this on the dialtone (CSS/LESS) side though. perhaps we can still keep this prop here to override if necessary

I think this is the right way to do it, as the icon itself handles the sizing, we're just mapping the icon sizes to the avatar sizes.

If we do this with CSS, maybe we we'll have issues overriding the size with the `iconSize` prop, don't you think?

**Comment by braddialpad** [comment]
> I think this is the right way to do it, as the icon itself handles the sizing, we're just mapping the icon sizes to the avatar sizes.
> 
> If we do this with CSS, maybe we we'll have issues overriding the size with the `iconSize` prop, don't you think?

Yeah true because we pass into the dt-icon component which always has a size... I think this could be done via css but might require some restructuring. Fine to do this for now, but we do need to update the examples on dialpad.design to have icon sizes applied then because right now it looks like this:

Screenshot 2023-08-28 at 10 38 55 AM

**Comment by juliodialpad** [comment]
> > I think this is the right way to do it, as the icon itself handles the sizing, we're just mapping the icon sizes to the avatar sizes.
> > If we do this with CSS, maybe we we'll have issues overriding the size with the `iconSize` prop, don't you think?
> 
> Yeah true because we pass into the dt-icon component which always has a size... I think this could be done via css but might require some restructuring. Fine to do this for now, but we do need to update the examples on dialpad.design to have icon sizes applied then because right now it looks like this:
> 
> Screenshot 2023-08-28 at 10 38 55 AM

Yeah, I think once this is release and updated on dialtone, it should be updated automatically, if not, I'll fix it anyways while updating dialtone-vue on dialtone.

**Comment by braddialpad** [comment]
> Yeah, I think once this is release and updated on dialtone, it should be updated automatically, if not, I'll fix it anyways while updating dialtone-vue on dialtone.

Oh is this actually displaying via the vue component? In that case we should still update the code example to apply an icon size, because if you were to copy the html that is there it would not match the component example.

though I guess it doesn't really show the icon code there.. only the wrapping avatar classes.

**Review by braddialpad — APPROVED** [review]

**Comment by juliodialpad** [comment]
> > Yeah, I think once this is release and updated on dialtone, it should be updated automatically, if not, I'll fix it anyways while updating dialtone-vue on dialtone.
> 
> Oh is this actually displaying via the vue component? In that case we should still update the code example to apply an icon size, because if you were to copy the html that is there it would not match the component example.
> 
> though I guess it doesn't really show the icon code there.. only the wrapping avatar classes.

Will do the corresponding updates on dialtone if needed.

**Pull request merged**
