### PR TITLE
fix(callbox, avatar): events and styling

### PR DESCRIPTION
**Pull request by juliodialpad**
# Fix (Callbox, Avatar): Events and styling

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

- Removed `.stop` modifier from click events to allow click events to bubble up.
- Added `emits` to callbox to avoid duplicating native click event on vue 3
- Changed clickable title styling to use underline instead of background color on :hover and :active.
- Updated callbox variants to use `<dt-stack>` instead of custom divs with `d-d-flex`

## :bulb: Context

Received [design feedback](https://dialpad.atlassian.net/browse/DP-81452) on callbox implementation
Received a [bug report](https://dialpad.atlassian.net/browse/DP-81391) that avatar wasn't triggering the click event correctly.

## :pencil: Checklist

- [x] I have reviewed my changes
- [ ] I have added tests
- [ ] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [x] I have validated components keyboard navigation
- [ ] I have considered the performance impact of my change
- [ ] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

## :crystal_ball: Next Steps

Release and update on product.

## :camera: Screenshots / GIFs

image
image

### CODE REVIEW

**Comment by francisrupert** [comment]
@juliodialpad,

Underline is good. Can you update all the Critical (née Danger) buttons to use the regular critical/danger buttons?

https://github.com/dialpad/dialtone-vue/assets/1165933/465a7029-17ef-4f32-8e48-4e5ef49d5b1a

**Comment by juliodialpad** [comment]
> @juliodialpad,
> 
> Underline is good. Can you update all the Critical (née Danger) buttons to use the regular critical/danger buttons?
> 
>  callbox-critical-buttons.mov

changed, don't know what I was thinking while creating this haha sorry

**Comment by francisrupert** [comment]
@juliodialpad,

Yep, critical buttons spot-on. Incidentally, the hover/active bgcolor for those were a bug (far too light), and I just updated that in the Design Tokens via https://github.com/dialpad/dialtone-tokens/commit/00902ebc7a0d2fe57d847906c635cfe26ee21f46. 

I approve of the visual of these changes, defer to PR approval from others given the Vue changes. (oh, and good call converting to `dt-stack`, do that as often as possible _everywhere_).

**Comment by braddialpad** [comment]
> and I just updated that in the Design Tokens via [dialpad/dialtone-tokens@00902eb](https://github.com/dialpad/dialtone-tokens/commit/00902ebc7a0d2fe57d847906c635cfe26ee21f46).

Great, I'll do a new release of this.

**Review by braddialpad — COMMENTED** [review]
@juliodialpad Code looks good but please see my comment on percy.

**Review by iropolo — APPROVED** [review]
Pre-approving it but it is necessary to check percy issue

**Comment by juliodialpad** [comment]
> @juliodialpad Code looks good but please see my comment on percy.

Assumed that `<dt-stack>` component would align items, added `d-ai-center` class to center the items vertically.

**Comment by iropolo** [comment]
> > @juliodialpad Code looks good but please see my comment on percy.
> 
> Assumed that `<dt-stack>` component would align items, added `d-ai-center` class to center the items vertically.

If that's an expected behaviour of `dt-stack` maybe this addition should be added as an improvement to the component.
Not sure about it. Maybe design could enlighten us.

**Comment by braddialpad** [comment]
> Assumed that `<dt-stack>` component would align items, added `d-ai-center` class to center the items vertically.
> 

Hmm I think this probably is a good idea.. It would need to be possible to override it as well though

**Comment by juliodialpad** [comment]
> > Assumed that `<dt-stack>` component would align items, added `d-ai-center` class to center the items vertically.
> 
> Hmm I think this probably is a good idea.. It would need to be possible to override it as well though

Yes, maybe a prop called `alignment`, created a ticket so we don't forgot to do this: https://dialpad.atlassian.net/browse/DLT-1265

**Comment by francisrupert** [comment]
> Yes, maybe a prop called `alignment`...

I've [added comments on that task](https://dialpad.atlassian.net/browse/DLT-1265?focusedCommentId=799789) too.

**Pull request merged**
