### PR TITLE
chore: enable only inline component tests

### PR DESCRIPTION
**Pull request by braddialpad**
Vue 3

### CODE REVIEW

**Review by juliodialpad — COMMENTED** [review]
Why are initials displaying instead of images on avatars? I can't find any change related to removing those.

**Comment by braddialpad** [comment]
> Why are initials displaying instead of images on avatars? I can't find any change related to removing those.

Yeah.. this is one of the things that keeps flaking out.. sometimes it shows like that sometimes it doesn't.

**Comment by braddialpad** [comment]
Gonna try removing this 250 wait...

**Comment by braddialpad** [comment]
Seems okay now??

**Pull request merged**
