### PR TITLE
feat(leftbar): fixes and additions to leftbar row components

### PR DESCRIPTION
**Pull request by braddialpad**
Vue 3 of https://github.com/dialpad/dialtone-vue/pull/804

### CODE REVIEW

**Comment by juliodialpad** [comment]
image

The focus ring is looking a bit off I think. It doesn't look like a circle

**Comment by juliodialpad** [comment]
Vue 2
image

Vue 3 version
image

Also tooltip doesn't look ok.

**Comment by braddialpad** [comment]
looks like tooltip arrow is broken in prod.. logging an issue.

**Comment by braddialpad** [comment]
Merging this as it's causing issues with subsequent related commits being copied over to vue 3 branch. will fix in separate PR.

**Pull request merged**
