### PR TITLE
feat(feed-item-row): state changes - vue3

### PR DESCRIPTION
**Pull request by sanjeevdialpad**
# State changes for feed item row Vue3

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

States include:
1. Searched
2. ERROR
3. Normal

Every state other than normal can be faded using a method .fade() 

## :pencil: Checklist

- [ ] I have reviewed my changes
- [ ] I have added tests
- [ ] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [ ] I have validated components keyboard navigation
- [ ] I have considered the performance impact of my change
- [ ] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

### CODE REVIEW

**Review by braddialpad — APPROVED** [review]

**Review by iropolo — APPROVED** [review]

**Comment by sanjeevdialpad** [comment]
the actions are stuck and am not able to merge. any idea how i can force it? @braddialpad

**Comment by juliodialpad** [comment]
> the actions are stuck and am not able to merge. any idea how i can force it? @braddialpad

This is weird, let me investigate a bit, but I'll merge this for you if I don't find a solution quickly

**Comment by juliodialpad** [comment]
This issue was due to GitHub outage, whenever you have a problem like this, check the [GitHub status page](https://www.githubstatus.com/)

image

**Comment by sanjeevdialpad** [comment]
ty @juliodialpad I tried changing the description and not the title in hopes to trigger the actions. There surely must be a manual way to do so !
But thanks again.

**Pull request merged**
