### PR TITLE
feat(datepicker): date format utils

### PR DESCRIPTION
**Pull request by iropolo**
# Date format utils

## :hammer_and_wrench: Type Of Change

- [x] Feature

## :book: Description

We expose date utils format following https://dialpad.design/guides/writing-guidelines/#dates

https://dialpad.atlassian.net/browse/DLT-721

### CODE REVIEW

**Comment by iropolo** [comment]
Hmm... why in the preview the styles are not working correctly?
but in https://vue.dialpad.design/?path=/story/components-datepicker--default it does....

Local works properly

image

**Comment by braddialpad** [comment]
> Hmm... why in the preview the styles are not working correctly?

Hmm.. you are certainly getting some weird issues lately.. Maybe it doesn't like the scoped styles? Try unscoped styles

**Comment by iropolo** [comment]
> > Hmm... why in the preview the styles are not working correctly?
> 
> Hmm.. you are certainly getting some weird issues lately.. Maybe it doesn't like the scoped styles? Try unscoped styles

The styles are just for the table and they are in the default template, I dont think it is related or maybe you are talking about something else.

I would like to merge this and I will deploy it. Will see if this is sth internal of the preview or.. sth else...

... But ye lemme check it... strange solutions for strange issues, lets see if it is works

**Comment by braddialpad** [comment]
> The styles are just for the table and they are in the default template, I dont think it is related or maybe you are talking about something else.

Yeah I know but sometimes weird stuff happens so it might be worth trying. I only mentioned because we don't used scoped CSS often so it's something that is different from normal.

**Comment by iropolo** [comment]
> > The styles are just for the table and they are in the default template, I dont think it is related or maybe you are talking about something else.
> 
> Yeah I know but sometimes weird stuff happens so it might be worth trying. I only mentioned because we don't used scoped CSS often so it's something that is different from normal.

image

Could be this related to the issue? seems like it is not installing dialtone vue dependencies idk..

**Comment by braddialpad** [comment]
> Could be this related to the issue? seems like it is not installing dialtone vue dependencies idk..

It doesn't need to install them when it makes a cache hit

**Comment by braddialpad** [comment]
We ever figure out what is going on here?

**Comment by iropolo** [comment]
> We ever figure out what is going on here?

Same as #1061 

1. Dialtone wasn't updated with emoji-picker and datepicker styles (now is updated).
2. Emojipicker and datepicker are using `dt-` (dialtone 8 styles) they will not work.

Local datepicker in staging branch

image

Local emojipicker in staging-vue3 branch

image

**Comment by braddialpad** [comment]
> Same as #1061
> 
> 1. Dialtone wasn't updated with emoji-picker and datepicker styles (now is updated).
> 2. Emojipicker and datepicker are using `dt-` (dialtone 8 styles) they will not work.
> 
> Local datepicker in staging branch
> 
> image
> Local emojipicker in staging-vue3 branch
> 
> image

I think we'll need to change the variables to work on the dialtone 7 branch. The changes to dt- variables should only be on the "dialtone-8" branch

**Review by braddialpad — APPROVED** [review]

**Comment by iropolo** [comment]
Styles migrations will be tackled in another PR. Because this one is not related to that.

**Pull request merged**
