### PR TITLE
feat(avatar): add canvasClass prop

### PR DESCRIPTION
**Pull request by braddialpad**
# feat(avatar): add canvasClass prop

## :hammer_and_wrench: Type Of Change

- [ ] Fix
- [x] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

Adding canvasClass to avatar so DPM can set a custom size as mentioned in this ticket https://dialpad.atlassian.net/browse/DT-954

### CODE REVIEW

**Review by iropolo — APPROVED** [review]
LGTM

**Review by juliodialpad — COMMENTED** [review]
This is going to give too much freedom on what you can do with Avatar, wouldn't be better to add like a 'custom-size' prop if we only need to change the size?

Or maybe adding something like 2x, 4x and 8x sizes.

**Comment by braddialpad** [comment]
> This is going to give too much freedom on what you can do with Avatar, wouldn't be better to add like a 'custom-size' prop if we only need to change the size?
> 
> Or maybe adding something like 2x, 4x and 8x sizes.

I actually think it remains more hidden doing it this way. If I add a dedicated size prop they're going to start randomly changing avatar sizes all over the place just because they see that prop 😆

**Comment by juliodialpad** [comment]
> > This is going to give too much freedom on what you can do with Avatar, wouldn't be better to add like a 'custom-size' prop if we only need to change the size?
> > Or maybe adding something like 2x, 4x and 8x sizes.
> 
> I actually think it remains more hidden doing it this way. If I add a dedicated size prop they're going to start randomly changing avatar sizes all over the place just because they see that prop 😆

Sounds fair 😅 go ahead and merge then.

**Pull request merged**
