### PR TITLE
fix: test script

### PR DESCRIPTION
**Pull request by iropolo**
# Fix: test script

## :hammer_and_wrench: Type Of Change

- [x] Fix

## :book: Description

Test fix for [DT-1097](https://dialpad.atlassian.net/browse/DT-1097)

Updated vue test utils library from "@vue/test-utils": "1.3" to "@vue/test-utils": "^1.3.4",

[DT-1097]: https://dialpad.atlassian.net/browse/DT-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by juliodialpad** [comment]
Remember to add `no-visual-tests` tag if there's no need to visual test this.

**Comment by juliodialpad** [comment]
There is still no summary at the end of tests, right? Or am I missing something?

**Comment by braddialpad** [comment]
> There is still no summary at the end of tests, right? Or am I missing something?

Yeah I get this also. Checked out this branch and ran `npm run install:all`

Screenshot 2023-03-28 at 12 21 56 PM

**Comment by braddialpad** [comment]
Unfortunately I still get the freeze / no report after deleting node_modules and reinstalling.

**Comment by braddialpad** [comment]
hmm not sure what to do about this one @iropolo it is going to be hard for you to fix if you can't repro it anymore. Maybe I'll try messing with it tomorrow.

**Comment by braddialpad** [comment]
Closing this since I have a PR up to migrate to jest.

**Pull request closed without merging**
