### PR TITLE
fix: href on link

### PR DESCRIPTION
**Pull request by sanjeevdialpad**
# fix: ability to not navigate when href is not passed to dt-link - vue3

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

We will reuse dt-link on mention for message input in which case we do not want to navigate anywhere else. this change will allow to do that coupled with the native event link so user can do specific actions without navigating away.

### CODE REVIEW

**Review by braddialpad — APPROVED** [review]

**Comment by iropolo** [comment]
VIsual test failing check disabled by adding 'no-visual-test' label to PR.
Accessibility Test failing, due this update? @sanjeevdialpad

**Comment by iropolo** [comment]
it will be necessary to replicate this change on Vue2 version? @sanjeevdialpad

**Review by iropolo — APPROVED** [review]
Pre-approved.

**Comment by braddialpad** [comment]
> t will be necessary to replicate this change on Vue2 version? @sanjeevdialpad

Just needs to merge in staging-vue3 to fix the accessibility tests

**Comment by iropolo** [comment]
Oh, okay cool, ye I just saw there is the vue2 version of it, it is #1244 
Please put -vue3 on PR title or mention the vue2 version in the description next time please. Thanks!

**Pull request merged**
