### PR TITLE
fix(contact-info): avatar's border color - vue 3

### PR DESCRIPTION
**Pull request by juliodialpad**
# Vue 3 version of #1097

### CODE REVIEW

**Comment by iropolo** [comment]
hmm preview not working here...

**Comment by iropolo** [comment]
rerunning it...

**Review by iropolo — APPROVED** [review]
Preview not working but seems is not related to the changes 🤷

**Comment by juliodialpad** [comment]
> Preview not working but seems is not related to the changes 🤷

The preview takes like 2 minutes after the message is posted here to be really deployed

**Pull request merged**
